### PR TITLE
Add plugin for gepetto-viewer

### PR DESCRIPTION
**Pull request by jmirabel**
This PR add a first version of a plugin for gepetto-viewer.

For now, the plugin displays the tree of frame and provides a way of displaying frames.

I had the intention (but not the time) to make the joint values modifiable.

### CODE REVIEW

**Comment by jmirabel** [comment]
Screenshot from 2021-03-05 09-45-44

**Comment by jcarpent** [comment]
> I had the intention (but not the time) to make the joint values modifiable.

What should be done for that?

**Comment by jmirabel** [comment]
One has to write Qt delegates, similarly to class `JointItemDelegate` in this file https://github.com/humanoid-path-planner/hpp-gui/blob/devel/plugins/hppwidgetsplugin/joint-tree-item.cc

**Comment by jmirabel** [comment]
The only difficulty is to correctly deal with the different type of joints. I think the best is to implement one delegate per lie group, using the LieGroup::integrate method, and then use the default lie group map to associate joint type to lie group types.

**Pull request merged**
